services:
  - type: web
    name: youtube-lowview-finder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
